### PR TITLE
Fix #10: Added magics to provide LDFLAGS and CFLAGS to gcc

### LINKED ISSUE #10: Allow user to pass flags to the compiler

### PR DESCRIPTION
**Pull request by spoorcc**
This PR implements fix for #10. Adds support for passing linker flags and cflags to gcc.
Ipython notebooks use magics for passing flags. This PR makes CKernel filter out lines starting with  `//%` after which key value pair can be added e.g.:
* `//% LDFLAGS: -lm`
* `//% CFLAGS: -Werror`

Currently only `LDFLAGS` and `CFLAGS` are accepted (case-insensitive), but this can be extended later on for more.

# Passing cflags example
```c
//% cflags: -Werror
int main() {
    printf("Hello world\n");
}
```
This will now result in failed run since `-Werror` makes the warning an error:
> `error: incompatible implicit declaration of built-in function ‘printf’ [-Werror]`

# Passing ldflags example:
When you for instance need stdmath for showing the `sin` or `cos` functions, LDFLAG `-lm` needs to be provide to gcc. Following code will now be compiled, linked and run succesfully.
```c
//% ldflags: -lm
/* cos example */
#include <stdio.h>      /* printf */
#include <math.h>       /* cos */

#define PI 3.14159265

int main ()
{
  double param, result;
  param = 60.0;
  result = cos ( param * PI / 180.0 );
  printf ("The cosine of %f degrees is %f.\n", param, result );
  return 0;
}
```

### CODE REVIEW

**Comment by brendan-rius** [comment]
Thank you!

**Comment by spoorcc** [comment]
No problem!

**Comment by fedele** [comment]
For me it is not working.
Can you help?

**Comment by spoorcc** [comment]
What did you try?


On Wed, Jun 28, 2017, at 12:55, fedele wrote:
> For me it is not working.
>  Can you help?


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/brendan-rius/jupyter-c-kernel/pull/26#issuecomment-311626276

**Comment by fedele** [comment]
I used jupyterhubWith jupyter-notebook no problems
-------- Messaggio originale --------Da: Ben <notifications@github.com> Data: 28/06/17  15:54  (GMT+01:00) A: brendan-rius/jupyter-c-kernel <jupyter-c-kernel@noreply.github.com> Cc: fedele <fedele.stabile@fis.unical.it>, Comment <comment@noreply.github.com> Oggetto: Re: [brendan-rius/jupyter-c-kernel] Fix #10: Added magics to provide LDFLAGS and CFLAGS to gcc (#26) 
What did you try?





On Wed, Jun 28, 2017, at 12:55, fedele wrote:

> For me it is not working.

>  Can you help?





> — You are receiving this because you authored the thread. Reply to

> this email directly, view it on GitHub[1], or mute the thread[2].> 



Links:



  1. https://github.com/brendan-rius/jupyter-c-kernel/pull/26#issuecomment-311626276

**Comment by spoorcc** [comment]
- What was the contents of your cell?
- What was the output of your notebook?

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fedele** [comment]
I am not at office so I cannot be precise but seems that dont recognize //% line
-------- Messaggio originale --------Da: Ben <notifications@github.com> Data: 28/06/17  16:10  (GMT+01:00) A: brendan-rius/jupyter-c-kernel <jupyter-c-kernel@noreply.github.com> Cc: fedele <fedele.stabile@fis.unical.it>, Comment <comment@noreply.github.com> Oggetto: Re: [brendan-rius/jupyter-c-kernel] Fix #10: Added magics to provide LDFLAGS and CFLAGS to gcc (#26) 

What was the contents of your cell?
What was the output of your notebook?

Sent from my OnePlus ONEPLUS A5000 using FastHub

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/brendan-rius/jupyter-c-kernel","title":"brendan-rius/jupyter-c-kernel","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/brendan-rius/jupyter-c-kernel"}},"updates":{"snippets":[{"icon":"PERSON","message":"@spoorcc in #26: - What was the contents of your cell?\n- What was the output of your notebook?\n\n_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_"}],"action":{"name":"View Pull Request","url":"https://github.com/brendan-rius/jupyter-c-kernel/pull/26#issuecomment-311671470"}}}

**Comment by spoorcc** [comment]
All I can think of now is that you might be missing a space after the `//%`

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fedele** [comment]
No space lost..Ok tomorrow morning i will make tests
-------- Messaggio originale --------Da: Ben <notifications@github.com> Data: 28/06/17  17:20  (GMT+01:00) A: brendan-rius/jupyter-c-kernel <jupyter-c-kernel@noreply.github.com> Cc: fedele <fedele.stabile@fis.unical.it>, Comment <comment@noreply.github.com> Oggetto: Re: [brendan-rius/jupyter-c-kernel] Fix #10: Added magics to provide LDFLAGS and CFLAGS to gcc (#26) 
All I can think of now is that you might be missing a space after the //%
Sent from my OnePlus ONEPLUS A5000 using FastHub

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/brendan-rius/jupyter-c-kernel","title":"brendan-rius/jupyter-c-kernel","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/brendan-rius/jupyter-c-kernel"}},"updates":{"snippets":[{"icon":"PERSON","message":"@spoorcc in #26: All I can think of now is that you might be missing a space after the `//%`\n\n_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_"}],"action":{"name":"View Pull Request","url":"https://github.com/brendan-rius/jupyter-c-kernel/pull/26#issuecomment-311693387"}}}

**Comment by fedele** [comment]
This is the cell:
//% ldflags -lm
/* cos example */
#include <stdio.h>      /* printf */
#include <math.h>       /* cos */

#define PI 3.14159265

int main ()
{
  double param, result;
  param = 60.0;
  result = cos ( param * PI / 180.0 );
  printf ("The cosine of %f degrees is %f.\n", param, result );
  return 0;
}
This is the output:
/tmp/cc3XaGfn.o: nella funzione "main":
tmp7lldn3_c.c:(.text+0x34): riferimento non definito a "cos"
collect2: error: ld returned 1 exit status
[C kernel] GCC exited with code 1, the executable will not be executed

Fedele

Il giorno mer, 28/06/2017 alle 08.20 -0700, Ben ha scritto:

**Comment by spoorcc** [comment]
I think you are missing the colon `:`

``` //% ldflags: -lm```

**Comment by fedele** [comment]
No Brendan I don't know way there is no semicolon (cut and paste???
very stange situation)
In any way:
This is the cell:
//% ldflags: -lm
/* cos example */
#include <stdio.h>      /* printf */
#include <math.h>       /* cos */

#define PI 3.14159265

int main ()
{
  double param, result;
  param = 60.0;
  result = cos ( param * PI / 180.0 );
  printf ("The cosine of %f degrees is %f.\n", param, result );
  return 0;
}

and this is the output:

/tmp/cce8IUpq.o: nella funzione "main":
tmpqwxaqhw7.c:(.text+0x34): riferimento non definito a "cos"
collect2: error: ld returned 1 exit status
[C kernel] GCC exited with code 1, the executable will not be executed


remember I'm using jupyterhub

Il giorno gio, 29/06/2017 alle 08.04 +0000, Ben ha scritto:

**Comment by fedele** [comment]
Other tests made:
I was able to open a notebook locally on the machine in with I
installed jupyterhub
and also using
jupyter-notebook
the kernel does not interpret the //% line

# jupyter --version
4.3.0
# python -V
Python 2.7.5

Il giorno gio, 29/06/2017 alle 08.04 +0000, Ben ha scritto:

**Comment by fedele** [comment]
To be complete:
# python3 -V
Python 3.4.5

Il giorno gio, 29/06/2017 alle 08.04 +0000, Ben ha scritto:

**Comment by spoorcc** [comment]
Snap, I was hoping it was that easy, just missing a colon  :smile: 

* Did you check the magics parsing (this PR) is in the Jupyter-c-kernel code you are running? 
* Does the `//% cflags: -Werror` example from above work?

**Comment by fedele** [comment]
This is the cell:
//% cflags: -Werror
int main() {
    printf("Hello world\n");
}

This is the output:
tmp/tmpq9fw8z0t.c: In function ‘main’:
/tmp/tmpq9fw8z0t.c:3:5: warning: implicit declaration of function
‘printf’ [-Wimplicit-function-declaration]
     printf("Hello world\n");
     ^
/tmp/tmpq9fw8z0t.c:3:5: warning: incompatible implicit declaration of
built-in function ‘printf’ [enabled by default]
Hello world

Il giorno gio, 29/06/2017 alle 03.08 -0700, Ben ha scritto:

**Comment by fedele** [comment]
oops:
in my file /usr/lib/python3.4/site-packages/jupyter_c_kernel/kernel.py
there is no mention to the magic parsing....
I am absolutely certain that I have followed your instructions.
Can you help me?

Il giorno gio, 29/06/2017 alle 03.08 -0700, Ben ha scritto:

**Comment by spoorcc** [comment]
Great! Then it is probably not my fault :grinning: 

How did you install?

Using the install script:
```wget -O - https://raw.githubusercontent.com/brendan-rius/jupyter-c-kernel/master/install.sh | sh``` should give you the latest version from master.

**Comment by fedele** [comment]
I will try the wget command,
infact if I give
pip install jupyter-c-kernel
I have the file kernel.py without magic mention

Il giorno gio, 29/06/2017 alle 11.07 +0000, Ben ha scritto:

**Comment by spoorcc** [comment]
I created a new issue #29 to update it, to solve it for other people as well

**Comment by fedele** [comment]
If I use wget command
the content in /usr/lib/python3.4/site-
packages/jupyter_c_kernel/kernel.py 
does not contains any magic mention
....
how can I change the files manually?
 
Il giorno gio, 29/06/2017 alle 11.07 +0000, Ben ha scritto:

**Comment by fedele** [comment]
I installed the Fortran kernel,

can you help me to insert the Compilation Flags as in C kernel?

Fedele

 

Da: Ben [mailto:notifications@github.com] 
Inviato: giovedì 29 giugno 2017 13:12
A: brendan-rius/jupyter-c-kernel <jupyter-c-kernel@noreply.github.com>
Cc: fedele <fedele.stabile@fis.unical.it>; Comment <comment@noreply.github.com>
Oggetto: Re: [brendan-rius/jupyter-c-kernel] Fix #10: Added magics to provide LDFLAGS and CFLAGS to gcc (#26)

 

I created a new issue #29 <https://github.com/brendan-rius/jupyter-c-kernel/issues/29>  to update it, to solve it for other people as well

**Comment by spoorcc** [comment]
Github has some nice guides for instance:
- https://help.github.com/articles/fork-a-repo/
- https://guides.github.com/introduction/flow/

But I would recommend to create an issue, and propose your solution to the maintainer of the project if you're not completely sure.



_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fedele** [comment]
I was able to create a branch.
I hope this is correct.
Fedele

Il giorno ven, 30/06/2017 alle 03.28 -0700, Ben ha scritto:

**Pull request merged**
